name: Test setup-lune Action

on:
  push:
  workflow_dispatch:

jobs:
  test:
    name: Test setup-lune action 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run action
        uses: CompeyDev/setup-lune@main

      - name: Run lune
        run: lune --help
