name: Update setup-lune Repository

on:
  push:
  workflow_dispatch:

jobs:
  update:
    name: Update setup-lune action 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Unset GitHub auth configs
        run: git config --unset-all http.https://github.com/.extraheader

      - name: Clone remote
        run: git clone https://github.com/CompeyDev/setup-lune

      - name: Update sources
        run: rm -rf ./.git/ && shopt -s dotglob && cp -r package/action/* setup-lune/
        
      - name: Push changes
        run: |-
          git diff
          git config --global user.email "hi@devcomp.xyz"
          git config --global user.name "CI"
          git diff --quiet || (git add -u && git commit -m "sync: CompeyDev/lune-packaging (${{ github.sha }})")
          git push https://CompeyDev:${{ secrets.GH_AUTH_TOKEN }}@github.com/CompeyDev/setup-lune.git main
        working-directory: "setup-lune"
            
