name: Build for Android

on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
          fetch-tags: true

      - name: Install rustup
        run: "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y"

      - name: Build routine
        run: "chmod +x package/android/build.sh && package/android/build.sh"

      - name: Create build artifacts
        uses: actions/upload-artifact@v3
        with:
          path: lune-src/build/lune-*.zip
            
