name: Build Lune AppImage

on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        arch: ["x86_64", "aarch64"]
    
    name: Build the AppImage 
    runs-on: ubuntu-latest

    steps:
      - name: Runner info
        run: uname -ar
      
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set working directory
        run: cd ./package/appimage && export LUNE_VERSION=0.7.5

      - name: Build AppImage
        uses: lalten/run-on-arch-action@amd64-support
        id: buildimg
        with:
          arch: ${{ matrix.arch }}
          distro: ubuntu_latest
          dockerRunArgs: |
            --volume "${PWD}:/build"
          run: apt update && \ 
            apt install imagemagick file desktop-file-utils curl wget dpkg-dev unzip fuse libfuse2 && \
            cd /build && \ 
            ./pkg2appimage/pkg2appimage lune.yml && \
            mv ./lune/lune-$(uname -m).AppImage ./lune-$LUNE_VERSION-$(uname -m).AppImage


            
