name: AUR Test 
on: 
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copy AUR PKGBUILDs into testing dir
        run: cp -r package/aur/lune-bin/ package/aur/lune-git/ package/aur/lune/ test/aur/
        
      - run: ls test/aur

      - name: Setup docker CLI
        uses: actions-hub/docker/cli@master
        env:
          SKIP_LOGIN: true

      - name: Test
        run: docker build -t aur_test test/aur && docker run aur_test

