name: Homebrew Test
on: 
  push:
  workflow_dispatch:
  
jobs:
  test_precompiled:
    runs-on: macos-latest
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Test
        run: brew install lune && lune || exit 0

  test_source:
    runs-on: macos-latest
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Test
        run: brew install lune --build-from-source && lune || exit 0
