name: Test Packages
on: 
  push:
  workflow_dispatch:

jobs:
  aur:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup docker CLI
        uses: actions-hub/docker/cli@master
        env:
          SKIP_LOGIN: true

      - name: Test
        run: docker build -t aur_test test/aur && docker run aur_test

